export const LIBRARY_ADD_TRACK = "LIBRARY_ADD_TRACK";
export const LIBRARY_CHANGE_TRACKLIST = "LIBRARY_CHANGE_TRACKLIST";
export const LIBRARY_SET_TRACKLIST = "LIBRARY_SET_TRACKLIST";
export const LIBRARY_FETCHING = "LIBRARY_FETCHING";
export const LIBRARY_LOADING = "LIBRARY_LOADING";
export const LIBRARY_SET_DIRS = "LIBRARY_SET_DIRS";
export const LIBRARY_SET_DIRS_FILES = "LIBRARY_SET_DIRS_FILES";
export const ERROR_BUILDING_FILE_METADATA = "ERROR_BUILDING_FILE_METADATA";
export const ERROR_LOAD_LIBRARY = "FAILED_TO_LOAD_LIBRARY";
export const ERROR_LOADING_FILES = "ERROR_LOADING_FILES";

export const MUSIC_FORMAT = [".mp3", ".m4a", ".ogg", ".flac", ".wma", ".wmv"];