export const PLAYER_SET_CURRENT = "PLAYER_SET_CURRENT";
export const PLAYER_SET_PREVIOUS = "PLAYER_SET_PREVIOUS";
export const PLAYER_SET_NEXT = "PLAYER_SET_NEXT";
export const PLAYER_UPDATE_PROGRESS = "PLAYER_UPDATE_PROGRESS";
export const PLAYER_SET_DURATION = "PLAYER_SET_DURATION";