export const TRACK_SET = "TRACK_SET";
export const TRACK_REMOVE_AUDIO = "TRACK_REMOVE_AUDIO";
export const TRACK_SET_NEW_AUDIO = "TRACK_SET_NEW_AUDIO";
export const TRACK_SWITCH_AUDIO = "TRACK_SWITCH_AUDIO";