export const TRACK_SET = "TRACK_SET";
export const TRACK_SET_QUEUE = "TRACK_SET_QUEUE";
export const TRACK_SHUFFLE_QUEUE = "TRACK_SHUFFLE_QUEUE";
export const TRACK_REMOVE_AUDIO = "TRACK_REMOVE_AUDIO";
export const TRACK_SET_NEW_AUDIO = "TRACK_SET_NEW_AUDIO";
export const TRACK_SWITCH_AUDIO = "TRACK_SWITCH_AUDIO";
export const TRACK_COPY_QUEUE = "TRACK_COPY_QUEUE";
