export const YOUTUBE_FETCH_IMAGE_URL_FAILED = "YOUTUBE_FETCH_IMAGE_URL_FAILED";
export const YOUTUBE_FETCH_INFO_FAILED = "YOUTUBE_FETCH_INFO_FAILED";
export const YOUTUBE_FETCH_INFO_SYNTAX_ERROR = "YOUTUBE_FETCH_INFO_SYNTAX_ERROR";
export const YOUTUBE_DOWNLOAD_IMAGE_FAILED = "YOUTUBE_DOWNLOAD_IMAGE_FAILED";
export const YOUTUBE_SET_IMAGE = "YOUTUBE_SET_IMAGE";
export const YOUTUBE_SET_INFO = "YOUTUBE_SET_INFO";