export const YOUTUBE_FETCH_IMAGE_URL_FAILED = "YOUTUBE_FETCH_IMAGE_URL_FAILED";
export const YOUTUBE_DOWNLOAD_IMAGE_FAILED = "YOUTUBE_DOWNLOAD_IMAGE_FAILED";
export const YOUTUBE_SET_IMAGE = "YOUTUBE_SET_IMAGE";